# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_established', models.IntegerField(max_length=4)),
                ('age', models.IntegerField(max_length=3)),
            ],
            options={
                'ordering': ('year_established',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('subgenre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('subgenre',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('song_length', models.IntegerField()),
                ('release_date', models.DateField()),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmvc.Album')),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmvc.Artist')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmvc.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicmvc.Genre'),
        ),
    ]
