# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicmvc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
